export const data = [
  {
    id: 0,
    name: "Ермак",
    version: "Меловой период",
    element: "Некро",
    rare: "Легендарная",
    type: "Маг",
    strength: 93,
    health: 78,
    speed: 50,
    mind: 12,
    class: "card-class-legend",
    img: "./imgData/ermacDino.png",
  },
  {
    id: 1,
    name: "Ермак",
    version: "Баг",
    element: "Некро",
    rare: "Легендарная",
    type: "Маг",
    strength: 36,
    health: 57,
    speed: 99,
    mind: 89,
    class: "card-class-legend",
    img: "./imgData/ermacError.png",
  },
  {
    id: 2,
    name: "Ермак",
    version: "Последний герой",
    element: "Некро",
    rare: "Легендарная",
    type: "Маг",
    strength: 81,
    health: 73,
    speed: 68,
    mind: 50,
    class: "card-class-legend",
    img: "./imgData/ermacHero.png",
  },
  {
    id: 3,
    name: "Ермак",
    version: "Лицемер",
    element: "Некро",
    rare: "Редкая",
    type: "Нежить",
    strength: 55,
    health: 80,
    speed: 60,
    mind: 80,
    class: "card-class-rare",
    img: "./imgData/ermacFacer.png",
  },
  {
    id: 4,
    name: "Ермак",
    version: "Рестлер",
    element: "Некро",
    rare: "Редкая",
    type: "Воин",
    strength: 85,
    health: 60,
    speed: 75,
    mind: 17,
    class: "card-class-rare",
    img: "./imgData/ermacBoxer.png",
  },
  {
    id: 5,
    name: "Ермак",
    version: "Классика",
    element: "Некро",
    rare: "Обычная",
    type: "Маг",
    strength: 48,
    health: 87,
    speed: 30,
    mind: 55,
    class: "card-class-cammon",
    img: "./imgData/ermacClassic.png",
  },
  {
    id: 6,
    name: "Ермак",
    version: "Зомби",
    element: "Некро",
    rare: "Обычная",
    type: "Нежить",
    strength: 37,
    health: 70,
    speed: 10,
    mind: 9,
    class: "card-class-cammon",
    img: "./imgData/ermacZombie.png",
  },
  {
    id: 7,
    name: "Ермак",
    version: "Дух глубин",
    element: "Некро",
    rare: "Эпическая",
    type: "Маг",
    strength: 86,
    health: 91,
    speed: 40,
    mind: 15,
    class: "card-class-epic",
    img: "./imgData/ermacWater.png",
  },
  {
    id: 8,
    name: "Ермак",
    version: "Нано-шаман",
    element: "Некро",
    rare: "Эпическая",
    type: "Кибер",
    strength: 52,
    health: 90,
    speed: 75,
    mind: 35,
    class: "card-class-epic",
    img: "./imgData/ermacCyber.png",
  },
  {
    id: 9,
    name: "Ермак",
    version: "Симбиот",
    element: "Некро",
    rare: "Эпическая",
    type: "Нежить",
    strength: 92,
    health: 89,
    speed: 75,
    mind: 15,
    class: "card-class-epic",
    img: "./imgData/ermacVenom.png",
  },
  {
    id: 10,
    name: "Барака",
    version: "Классика",
    element: "Нет",
    rare: "Обычная",
    type: "Воин",
    strength: 60,
    health: 48,
    speed: 34,
    mind: 20,
    class: "card-class-cammon",
    img: "./imgData/barakaClassic.png",
  },
  {
    id: 11,
    name: "Крок",
    version: "Защитник Амазонки",
    element: "Гидро, Некро",
    rare: "Эпическая",
    type: "Воин",
    strength: 81,
    health: 53,
    speed: 29,
    mind: 44,
    class: "card-class-epic",
    img: "./imgData/crocClassic.png",
  },
  {
    id: 12,
    name: "Ктулху",
    version: "Древний ужас",
    element: "Гидро",
    rare: "Эпическая",
    type: "Божество",
    strength: 92,
    health: 42,
    speed: 59,
    mind: 35,
    class: "card-class-epic",
    img: "./imgData/ktulhuClassic.png",
  },
  {
    id: 13,
    name: "Нуб Сайбот",
    version: "Посланник смерти",
    element: "Тени",
    rare: "Эпическая",
    type: "Нежить",
    strength: 64,
    health: 53,
    speed: 87,
    mind: 36,
    class: "card-class-epic",
    img: "./imgData/noobSaibotDeath.png",
  },
  {
    id: 14,
    name: "Нуб Сайбот",
    version: "Классика",
    element: "Тени",
    rare: "Обычная",
    type: "Нежить",
    strength: 54,
    health: 47,
    speed: 81,
    mind: 30,
    class: "card-class-cammon",
    img: "./imgData/noobSaibotClassic.png",
  },
  {
    id: 15,
    name: "Мистер Морж",
    version: "Чумной фанат",
    element: "Нет",
    rare: "Редкая",
    type: "Воин",
    strength: 70,
    health: 40,
    speed: 30,
    mind: 20,
    class: "card-class-rare",
    img: "./imgData/misterWalrus.png",
  },
  {
    id: 16,
    name: "Рептилия",
    version: "Посланник смерти",
    element: "Токс",
    rare: "Эпическая",
    type: "Нежить",
    strength: 29,
    health: 36,
    speed: 92,
    mind: 8,
    class: "card-class-epic",
    img: "./imgData/reptileDeath.png",
  },
  {
    id: 17,
    name: "Рептилия",
    version: "Болотный ящер",
    element: "Токс",
    rare: "Редкая",
    type: "Воин",
    strength: 56,
    health: 30,
    speed: 66,
    mind: 10,
    class: "card-class-rare",
    img: "./imgData/reptileAgo.png",
  },
  {
    id: 18,
    name: "Рептилия",
    version: "Классика",
    element: "Токс",
    rare: "Обычная",
    type: "Воин",
    strength: 63,
    health: 34,
    speed: 71,
    mind: 14,
    class: "card-class-cammon",
    img: "./imgData/reptileClassic.png",
  },
  {
    id: 19,
    name: "Рептилия",
    version: "Проклятие горгоны",
    element: "Каменный взор",
    rare: "Легендарная",
    type: "Божество",
    strength: 67,
    health: 46,
    speed: 23,
    mind: 34,
    class: "card-class-legend",
    img: "./imgData/reptileGorgone.png",
  },
  {
    id: 20,
    name: "Рейн",
    version: "Классика",
    element: "Гидро",
    rare: "Обычная",
    type: "Воин",
    strength: 51,
    health: 46,
    speed: 76,
    mind: 28,
    class: "card-class-cammon",
    img: "./imgData/rainClassic.png",
  },
  {
    id: 21,
    name: "Саб-Зиро",
    version: "Холодная война",
    element: "Крио",
    rare: "Эпическая",
    type: "Воин",
    strength: 76,
    health: 53,
    speed: 22,
    mind: 38,
    class: "card-class-epic",
    img: "./imgData/sub-zeroCaldWar.png",
  },
  {
    id: 22,
    name: "Саб-Зиро",
    version: "Посланник смерти",
    element: "Крио",
    rare: "Эпическая",
    type: "Нежить",
    strength: 86,
    health: 75,
    speed: 45,
    mind: 12,
    class: "card-class-epic",
    img: "./imgData/sub-zeroDeath.png",
  },
  {
    id: 23,
    name: "Саб-Зиро",
    version: "Ледниковый период",
    element: "Крио",
    rare: "Эпическая",
    type: "Воин",
    strength: 95,
    health: 32,
    speed: 25,
    mind: 40,
    class: "card-class-epic",
    img: "./imgData/sub-zeroAgo.png",
  },
  {
    id: 24,
    name: "Саб-Зиро",
    version: "Бурря",
    element: "Крио",
    rare: "Эпическая",
    type: "Воин",
    strength: 70,
    health: 50,
    speed: 20,
    mind: 37,
    class: "card-class-epic",
    img: "./imgData/sub-zeroBur.png",
  },
  {
    id: 25,
    name: "Саб-Зиро",
    version: "Полярный",
    element: "Крио",
    rare: "Редкая",
    type: "Воин",
    strength: 75,
    health: 70,
    speed: 68,
    mind: 30,
    class: "card-class-rare",
    img: "./imgData/sub-zeroPolar.png",
  },
  {
    id: 26,
    name: "Саб-Зиро",
    version: "Морозильник",
    element: "Крио",
    rare: "Редкая",
    type: "Кибер",
    strength: 67,
    health: 59,
    speed: 80,
    mind: 15,
    class: "card-class-rare",
    img: "./imgData/sub-zeroCyber.png",
  },
  {
    id: 27,
    name: "Саб-Зиро",
    version: "Классика",
    element: "Крио",
    rare: "Обычная",
    type: "Воин",
    strength: 55,
    health: 51,
    speed: 45,
    mind: 40,
    class: "card-class-cammon",
    img: "./imgData/sub-zeroClassic.png",
  },
  {
    id: 28,
    name: "Саб-Зиро",
    version: "Подводный ледник",
    element: "Крио",
    rare: "Легендарная",
    type: "Нежить",
    strength: 91,
    health: 75,
    speed: 43,
    mind: 30,
    class: "card-class-legend",
    img: "./imgData/sub-zeroWater.png",
  },
  {
    id: 29,
    name: "Саб-Зиро",
    version: "Зомби",
    element: "Крио",
    rare: "Обычная",
    type: "Нежить",
    strength: 46,
    health: 40,
    speed: 23,
    mind: 18,
    class: "card-class-cammon",
    img: "./imgData/sub-zeroZombie.png",
  },
  {
    id: 30,
    name: "Сайракс",
    version: "Классика",
    element: "Люкс",
    rare: "Обычная",
    type: "Кибер",
    strength: 60,
    health: 59,
    speed: 70,
    mind: 33,
    class: "card-class-cammon",
    img: "./imgData/sayraxClassic.png",
  },
  {
    id: 31,
    name: "Сектор",
    version: "Классика",
    element: "Пиро",
    rare: "Обычная",
    type: "Кибер",
    strength: 81,
    health: 73,
    speed: 53,
    mind: 33,
    class: "card-class-cammon",
    img: "./imgData/sektorClassic.png",
  },
  {
    id: 32,
    name: "Скорпион",
    version: "Гибрид",
    element: "Пиро, Токс",
    rare: "Легендарная",
    type: "Воин",
    strength: 70,
    health: 63,
    speed: 65,
    mind: 20,
    class: "card-class-legend",
    img: "./imgData/scorpionScorp.png",
  },
  {
    id: 33,
    name: "Скорпион",
    version: "Посланник смерти",
    element: "Пиро",
    rare: "Легендарная",
    type: "Нежить",
    strength: 96,
    health: 80,
    speed: 43,
    mind: 30,
    class: "card-class-legend",
    img: "./imgData/scorpionDeath.png",
  },
  {
    id: 34,
    name: "Скорпион",
    version: "Зомби",
    element: "Пиро",
    rare: "Обычная",
    type: "Нежить",
    strength: 47,
    health: 35,
    speed: 26,
    mind: 18,
    class: "card-class-cammon",
    img: "./imgData/scorpionZombie.png",
  },
  {
    id: 35,
    name: "Скорпион",
    version: "Классика",
    element: "Пиро",
    rare: "Обычная",
    type: "Воин",
    strength: 56,
    health: 50,
    speed: 55,
    mind: 30,
    class: "card-class-cammon",
    img: "./imgData/scorpionClassic.png",
  },
  {
    id: 36,
    name: "W1nty",
    version: "Классика",
    element: "Абсолют",
    rare: "Мифическая",
    type: "Божество",
    strength: 50,
    health: 50,
    speed: 50,
    mind: 50,
    class: "card-class-mythic",
    img: "./imgData/w1ntyClassic.png",
  },
  {
    id: 37,
    name: "Уран",
    version: "Эхо войны",
    element: "Нет",
    rare: "Эпическая",
    type: "Кибер",
    strength: 92,
    health: 53,
    speed: 39,
    mind: 33,
    class: "card-class-epic",
    img: "./imgData/uranCyber.png",
  },
  {
    id: 38,
    name: "Тремор",
    version: "Классика",
    element: "Гео",
    rare: "Обычная",
    type: "Воин",
    strength: 81,
    health: 70,
    speed: 30,
    mind: 18,
    class: "card-class-cammon",
    img: "./imgData/tremorClassic.png",
  },
  {
    id: 39,
    name: "Смоук",
    version: "Классика",
    element: "Анемо",
    rare: "Обычная",
    type: "Воин",
    strength: 56,
    health: 49,
    speed: 75,
    mind: 29,
    class: "card-class-cammon",
    img: "./imgData/smokeClassic.png",
  },
  {
    id: 40,
    name: "Смерть",
    version: "Императрица тьмы",
    element: "Некро",
    rare: "Легендарная",
    type: "Божество",
    strength: 90,
    health: 77,
    speed: 52,
    mind: 85,
    class: "card-class-legend",
    img: "./imgData/deathQueen.png",
  },
  {
    id: 41,
    name: "Скорпион",
    version: "Точка невозврата",
    element: "Пиро",
    rare: "Эпическая",
    type: "Нежить",
    strength: 86,
    health: 50,
    speed: 30,
    mind: 34,
    class: "card-class-epic",
    img: "./imgData/scorpionDemon.png",
  },
  {
    id: 42,
    name: "Скорпион",
    version: "Перегрев системы",
    element: "Пиро",
    rare: "Эпическая",
    type: "Кибер",
    strength: 80,
    health: 51,
    speed: 10,
    mind: 10,
    class: "card-class-epic",
    img: "./imgData/scorpionCyber.png",
  },
  {
    id: 43,
    name: "Скорпион",
    version: "Священное пламя времён",
    element: "Пиро",
    rare: "Редкая",
    type: "Воин",
    strength: 60,
    health: 50,
    speed: 80,
    mind: 21,
    class: "card-class-rare",
    img: "./imgData/scorpionAgo.png",
  },
  {
    id: 44,
    name: "Мор",
    version: "Алый Ужас",
    element: "Вампиризм",
    rare: "Легендарная",
    type: "Нежить",
    strength: 98,
    health: 85,
    speed: 92,
    mind: 70,
    class: "card-class-legend",
    img: "./imgData/morClassic.png",
  },
];
